<?php

use App\Http\Controllers\Api\Admin\AiLearningAdminController;
use App\Http\Controllers\Api\Admin\AIUsageController;
use App\Http\Controllers\Api\Admin\AiConfigController;
use App\Http\Controllers\Api\Admin\CompanyController;
use App\Http\Controllers\Api\Admin\ImpersonateController;
use App\Http\Controllers\Api\Admin\CmsAdminController;
use App\Http\Controllers\Api\Admin\LandingFaqController;
use App\Http\Controllers\Api\Admin\LogController;
use App\Http\Controllers\Api\Admin\OverviewController;
use App\Http\Controllers\Api\Admin\PaymentGatewayController;
use App\Http\Controllers\Api\Admin\PlatformSettingsController;
use App\Http\Controllers\Api\Admin\RevenueController;
use App\Http\Controllers\Api\Admin\TestimonialController;
use App\Http\Controllers\Api\Admin\UserController;
use App\Http\Controllers\Api\Admin\WhatsAppConnectionController;
use App\Http\Controllers\Api\AgentSdkController;
use App\Http\Controllers\Api\ChannelWebhookController;
use App\Http\Controllers\Api\WebWidgetController;
use App\Http\Controllers\Api\Company\ChannelIngestController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\Company\AgentTrustLogController;
use App\Http\Controllers\Api\Company\CommerceAgentEventController;
use App\Http\Controllers\Api\Company\CommerceSpecialistController;
use App\Http\Controllers\Api\Company\CompanyBrainController;
use App\Http\Controllers\Api\Company\CognitiveAiController;
use App\Http\Controllers\Api\Company\ExecutiveAiController;
use App\Http\Controllers\Api\Company\IntegrationController;
use App\Http\Controllers\Api\Company\KnowledgeVectorController;
use App\Http\Controllers\Api\Company\IntelligenceController;
use App\Http\Controllers\Api\Company\BusinessGraphController;
use App\Http\Controllers\Api\Company\BusinessTimelineController;
use App\Http\Controllers\Api\Company\CommerceBriefController;
use App\Http\Controllers\Api\Company\CommerceExperimentController;
use App\Http\Controllers\Api\Company\CompanyAiProviderController;
use App\Http\Controllers\Api\Company\CompanyAiUsageController;
use App\Http\Controllers\Api\Company\ApiPlatformController;
use App\Http\Controllers\Api\Company\ApiV1Controller;
use App\Http\Controllers\Api\Company\AiModelController;
use App\Http\Controllers\Api\Company\ChatController;
use App\Http\Controllers\Api\Company\ChatMessageController;
use App\Http\Controllers\Api\Company\WhatsAppCampaignController;
use App\Http\Controllers\Api\Company\CustomerController;
use App\Http\Controllers\Api\Admin\GrowthPortfolioController;
use App\Http\Controllers\Api\Admin\SystemHealthController;
use App\Http\Controllers\Api\Company\ExportController;
use App\Http\Controllers\Api\Company\GrowthAdSpendController;
use App\Http\Controllers\Api\Company\GrowthAgentController;
use App\Http\Controllers\Api\Company\AnalyticsController;
use App\Http\Controllers\Api\Company\GrowthAnalyticsController;
use App\Http\Controllers\Api\Company\GrowthCompetitorController;
use App\Http\Controllers\Api\Company\GrowthInsightController;
use App\Http\Controllers\Api\Company\GrowthIntegrationController;
use App\Http\Controllers\Api\Company\GrowthIntelligenceController;
use App\Http\Controllers\Api\Company\GrowthMetaController;
use App\Http\Controllers\Api\Company\GrowthPostController;
use App\Http\Controllers\Api\Company\GrowthSocialController;
use App\Http\Controllers\Api\Company\FaqController;
use App\Http\Controllers\Api\Company\ImportController;
use App\Http\Controllers\Api\Company\MemorySearchController;
use App\Http\Controllers\Api\Company\MarketplaceController;
use App\Http\Controllers\Api\Company\MissionControlController;
use App\Http\Controllers\Api\Company\MpesaCheckoutController;
use App\Http\Controllers\Api\Company\OnboardingInterviewController;
use App\Http\Controllers\Api\Company\PolicyRuleController;
use App\Http\Controllers\Api\Company\NotificationController;
use App\Http\Controllers\Api\Company\OrderController;
use App\Http\Controllers\Api\Company\OwnerAnalyticsController;
use App\Http\Controllers\Api\Company\PaystackCheckoutController;
use App\Http\Controllers\Api\Company\ProductController;
use App\Http\Controllers\Api\Company\SettingsController;
use App\Http\Controllers\Api\Company\StripeCheckoutController;
use App\Http\Controllers\Api\Company\SubscriptionController;
use App\Http\Controllers\Api\Company\TeamController;
use App\Http\Controllers\Api\Company\WhatsAppController;
use App\Http\Controllers\Api\Company\WhatsAppTemplateController;
use App\Http\Controllers\Api\EmailVerificationController;
use App\Http\Controllers\Api\AppBrandingController;
use App\Http\Controllers\Api\CmsPageController;
use App\Http\Controllers\Api\ContactController;
use App\Http\Controllers\Api\LandingController;
use App\Http\Controllers\Api\MpesaCallbackController;
use App\Http\Controllers\Api\PaystackWebhookController;
use App\Http\Controllers\Api\PlanController;
use App\Http\Controllers\Api\StripeWebhookController;
use App\Http\Controllers\Api\WhatsAppWebhookController;
use Illuminate\Support\Facades\Route;

// Public (no auth)
Route::get('plans', [PlanController::class, 'index']);
Route::get('app-branding', [AppBrandingController::class, 'show']);
Route::get('cms/pages/{slug}', [CmsPageController::class, 'show']);
Route::get('cms/global', [CmsPageController::class, 'global']);
Route::post('contact', [ContactController::class, 'store'])->middleware('throttle:10,1');
Route::get('landing', [LandingController::class, 'index']);

// Stripe webhook (no auth; verified by Stripe signature)
Route::post('stripe/webhook', StripeWebhookController::class);

// M-Pesa callback (no auth; called by Safaricom)
Route::post('mpesa/callback', MpesaCallbackController::class);

// Paystack webhook (no auth; verified by HMAC signature)
Route::post('paystack/webhook', PaystackWebhookController::class);

// WhatsApp webhook (no auth; Meta calls for verification and incoming messages)
Route::get('whatsapp/webhook', [WhatsAppWebhookController::class, 'verify']);
Route::post('whatsapp/webhook', [WhatsAppWebhookController::class, 'receive']);

// Auth (no auth required)
Route::prefix('auth')->group(function () {
    Route::get('verify-email', EmailVerificationController::class)->name('api.verification.verify');
    Route::middleware('throttle:auth-login')->post('login', [AuthController::class, 'login']);
    Route::middleware('throttle:auth-register')->post('register', [AuthController::class, 'register']);
    Route::middleware('throttle:auth-password')->group(function () {
        Route::post('forgot-password', [AuthController::class, 'forgotPassword']);
        Route::post('reset-password', [AuthController::class, 'resetPassword']);
        Route::post('resend-verification', [AuthController::class, 'resendVerification']);
    });
    Route::middleware(['auth:sanctum', 'user.active'])->group(function () {
        Route::get('me', [AuthController::class, 'me']);
        Route::put('profile', [AuthController::class, 'updateProfile']);
        Route::put('password', [AuthController::class, 'updatePassword']);
        Route::post('logout', [AuthController::class, 'logout']);
    });
});

// Public web widget (token auth per company)
Route::middleware('throttle:60,1')->group(function () {
    Route::get('public/web-widget/config', [WebWidgetController::class, 'config']);
    Route::post('public/web-widget/message', [WebWidgetController::class, 'message']);
    Route::get('agent-sdk/v1/manifest', [AgentSdkController::class, 'manifest']);
});

// Channel webhooks (ingest secret per company)
Route::middleware('throttle:120,1')->prefix('webhooks/channels/{companyId}')->group(function () {
    Route::post('email', [ChannelWebhookController::class, 'email']);
    Route::match(['GET', 'POST'], 'instagram-dm', [ChannelWebhookController::class, 'instagramDm']);
});

// Company API v1 (API key auth)
Route::prefix('v1/company')->middleware('api.key')->group(function () {
    Route::get('health', [ApiV1Controller::class, 'health']);
    Route::get('orders', [ApiV1Controller::class, 'orders']);
});

// Company (auth required; subscription must be active except for subscription/checkout routes)
Route::prefix('company')->middleware(['auth:sanctum', 'user.active', 'subscription.active'])->group(function () {
    Route::get('chats', [ChatController::class, 'index']);
    Route::post('chats/start', [ChatController::class, 'start']);
    Route::post('chats/{chatId}/hand-back', [ChatController::class, 'handBack']);
    Route::get('chats/{chatId}/messages', [ChatMessageController::class, 'index']);
    Route::post('chats/{chatId}/messages', [ChatMessageController::class, 'store']);
    Route::post('chats/{chatId}/messages/{messageId}/learning-feedback', [ChatMessageController::class, 'learningFeedback']);
    Route::get('orders', [OrderController::class, 'index']);
    Route::get('orders/{order}', [OrderController::class, 'show']);
    Route::post('orders', [OrderController::class, 'store']);
    Route::patch('orders/{order}', [OrderController::class, 'updateStatus']);
    Route::get('customers/stats', [CustomerController::class, 'stats']);
    Route::get('customers', [CustomerController::class, 'index']);
    Route::get('products', [ProductController::class, 'index']);
    Route::post('products/{product}/variants', [ProductController::class, 'storeVariant']);
    Route::put('product-variants/{productVariant}', [ProductController::class, 'updateVariant']);
    Route::delete('product-variants/{productVariant}', [ProductController::class, 'destroyVariant']);
    Route::post('products/{product}/images', [ProductController::class, 'storeProductImage']);
    Route::post('product-variants/{productVariant}/images', [ProductController::class, 'storeVariantImage']);
    Route::put('product-images/{productImage}', [ProductController::class, 'updateImage']);
    Route::delete('product-images/{productImage}', [ProductController::class, 'destroyImage']);
    // POST alias for update: PHP does not populate $_FILES on multipart PUT; browsers send file uploads as POST.
    Route::post('products/{product}', [ProductController::class, 'update']);
    Route::apiResource('products', ProductController::class)->only(['store', 'update', 'destroy']);
    Route::get('faqs', [FaqController::class, 'index']);
    Route::apiResource('faqs', FaqController::class)->only(['store', 'update', 'destroy']);
    Route::get('analytics', [\App\Http\Controllers\Api\Company\AnalyticsController::class, 'index']);
    Route::get('growth/analytics', [GrowthAnalyticsController::class, 'index']);
    Route::get('growth/posts', [GrowthPostController::class, 'index']);
    Route::post('growth/posts', [GrowthPostController::class, 'store']);
    Route::post('growth/content/generate', [GrowthPostController::class, 'generate']);
    Route::post('growth/content/generate-smart', [GrowthIntelligenceController::class, 'generateSmart']);
    Route::get('growth/intelligence/patterns', [GrowthIntelligenceController::class, 'patterns']);
    Route::post('growth/intelligence/patterns/extract', [GrowthIntelligenceController::class, 'extractPatterns']);
    Route::post('growth/intelligence/patterns/queue', [GrowthIntelligenceController::class, 'queueExtractPatterns']);
    Route::post('growth/intelligence/patterns/{pattern}/apply', [GrowthIntelligenceController::class, 'applyPattern']);
    Route::get('growth/intelligence/content-mix', [GrowthIntelligenceController::class, 'contentMix']);
    Route::get('growth/intelligence/weekly-brief', [GrowthIntelligenceController::class, 'weeklyBrief']);
    Route::get('growth/intelligence/score-drafts', [GrowthIntelligenceController::class, 'scoreDrafts']);
    Route::get('growth/intelligence/summary', [GrowthIntelligenceController::class, 'intelligenceSummary']);
    Route::get('growth/intelligence/prediction-accuracy', [GrowthIntelligenceController::class, 'predictionAccuracy']);
    Route::get('growth/intelligence/portfolio-insights', [GrowthIntelligenceController::class, 'portfolioInsights']);
    Route::post('growth/intelligence/generate-variants', [GrowthIntelligenceController::class, 'generateVariants']);
    Route::get('growth/export/attribution', [GrowthIntelligenceController::class, 'exportAttribution']);
    Route::post('growth/intelligence/execute-mix', [GrowthIntelligenceController::class, 'executeMixPlan']);
    Route::post('growth/posts/{post}/approve', [GrowthPostController::class, 'approve']);
    Route::post('growth/posts/{post}/schedule', [GrowthPostController::class, 'schedule']);
    Route::post('growth/posts/{post}/publish', [GrowthPostController::class, 'publish']);
    Route::post('growth/posts/{post}/image', [GrowthPostController::class, 'uploadImage']);
    Route::post('growth/posts/{post}/generate-image', [GrowthPostController::class, 'generateImage']);
    Route::get('growth/posts/{post}/share-package', [GrowthPostController::class, 'sharePackage']);
    Route::delete('growth/posts/{post}', [GrowthPostController::class, 'destroy']);
    Route::get('growth/social-accounts', [GrowthSocialController::class, 'index']);
    Route::get('growth/oauth/config', [GrowthSocialController::class, 'oauthConfig']);
    Route::get('growth/oauth/{platform}/authorize', [GrowthSocialController::class, 'oauthAuthorize']);
    Route::post('growth/social-accounts/connect', [GrowthSocialController::class, 'connect']);
    Route::post('growth/social-accounts/{account}/disconnect', [GrowthSocialController::class, 'disconnect']);
    Route::get('growth/ad-spend', [GrowthAdSpendController::class, 'index']);
    Route::post('growth/ad-spend', [GrowthAdSpendController::class, 'store']);
    Route::post('growth/ad-spend/import', [GrowthAdSpendController::class, 'import']);
    Route::delete('growth/ad-spend/{entry}', [GrowthAdSpendController::class, 'destroy']);
    Route::get('growth/insights', [GrowthInsightController::class, 'index']);
    Route::post('growth/insights/generate', [GrowthInsightController::class, 'generate']);
    Route::post('growth/insights/{insight}/read', [GrowthInsightController::class, 'markRead']);
    Route::get('growth/competitors', [GrowthCompetitorController::class, 'index']);
    Route::post('growth/competitors', [GrowthCompetitorController::class, 'store']);
    Route::delete('growth/competitors/{competitor}', [GrowthCompetitorController::class, 'destroy']);
    Route::get('growth/agents', [GrowthAgentController::class, 'index']);
    Route::post('growth/agents/run', [GrowthAgentController::class, 'runPipeline']);
    Route::get('growth/pilot', [GrowthMetaController::class, 'pilotStatus']);
    Route::get('growth/onboarding', [GrowthMetaController::class, 'onboarding']);
    Route::get('growth/meta/pages', [GrowthMetaController::class, 'pages']);
    Route::post('growth/meta/select-page', [GrowthMetaController::class, 'selectPage']);
    Route::get('growth/meta/ad-accounts', [GrowthMetaController::class, 'adAccounts']);
    Route::post('growth/meta/select-ad-account', [GrowthMetaController::class, 'selectAdAccount']);
    Route::post('growth/meta/sync-metrics', [GrowthMetaController::class, 'syncMetrics']);
    Route::post('growth/meta/sync-ads', [GrowthMetaController::class, 'syncAds']);
    Route::get('growth/crm/status', [GrowthMetaController::class, 'crmStatus']);
    Route::post('growth/crm/run', [GrowthMetaController::class, 'runCrmAgent']);
    Route::get('growth/integrations', [GrowthIntegrationController::class, 'index']);
    Route::post('growth/integrations/connect', [GrowthIntegrationController::class, 'connect']);
    Route::post('growth/integrations/sync', [GrowthIntegrationController::class, 'sync']);
    Route::get('subscription', [SubscriptionController::class, 'show']);
    Route::get('subscription/invoices', [SubscriptionController::class, 'invoices']);
    Route::get('subscription/usage', [SubscriptionController::class, 'usage']);
    Route::get('team', [TeamController::class, 'index']);
    Route::get('notifications', [NotificationController::class, 'index']);
    Route::post('notifications/read-all', [NotificationController::class, 'markAllRead']);
    Route::post('notifications/{notification}/read', [NotificationController::class, 'markRead']);
    Route::get('settings', [SettingsController::class, 'show']);
    Route::put('settings', [SettingsController::class, 'update']);
    Route::get('commerce-brief', [CommerceBriefController::class, 'today']);
    Route::get('executive-ai/dashboard', [ExecutiveAiController::class, 'dashboard']);
    Route::get('executive-ai/opportunities', [ExecutiveAiController::class, 'opportunities']);
    Route::get('executive-ai/approvals', [ExecutiveAiController::class, 'pendingApprovals']);
    Route::post('executive-ai/approvals/{id}/approve', [ExecutiveAiController::class, 'approve']);
    Route::post('executive-ai/approvals/{id}/reject', [ExecutiveAiController::class, 'reject']);
    Route::get('commerce-experiments', [CommerceExperimentController::class, 'index']);
    Route::post('commerce-experiments', [CommerceExperimentController::class, 'store']);
    Route::post('commerce-experiments/{experiment}/evaluate', [CommerceExperimentController::class, 'evaluate']);
    Route::get('cognitive-ai/dashboard', [CognitiveAiController::class, 'dashboard']);
    Route::get('cognitive-ai/strategic-memories', [CognitiveAiController::class, 'strategicMemories']);
    Route::post('cognitive-ai/plans', [CognitiveAiController::class, 'createPlan']);
    Route::post('cognitive-ai/simulate', [CognitiveAiController::class, 'simulate']);
    Route::post('intelligence/reason', [IntelligenceController::class, 'reason']);
    Route::get('intelligence/cases', [IntelligenceController::class, 'cases']);
    Route::get('intelligence/cases/{id}', [IntelligenceController::class, 'showCase']);
    Route::post('intelligence/outcomes', [IntelligenceController::class, 'recordOutcome']);
    Route::get('intelligence/outcomes', [IntelligenceController::class, 'outcomes']);
    Route::get('policy-rules', [PolicyRuleController::class, 'index']);
    Route::post('policy-rules', [PolicyRuleController::class, 'store']);
    Route::patch('policy-rules/{id}', [PolicyRuleController::class, 'update']);
    Route::delete('policy-rules/{id}', [PolicyRuleController::class, 'destroy']);
    Route::get('api-platform/keys', [ApiPlatformController::class, 'listApiKeys']);
    Route::post('api-platform/keys', [ApiPlatformController::class, 'createApiKey']);
    Route::delete('api-platform/keys/{id}', [ApiPlatformController::class, 'revokeApiKey']);
    Route::get('api-platform/webhooks', [ApiPlatformController::class, 'listWebhooks']);
    Route::post('api-platform/webhooks', [ApiPlatformController::class, 'createWebhook']);
    Route::get('api-platform/billing-history', [ApiPlatformController::class, 'billingHistory']);
    Route::get('commerce-specialists/runs', [CommerceSpecialistController::class, 'index']);
    Route::post('commerce-specialists/run', [CommerceSpecialistController::class, 'runPipeline']);
    Route::get('commerce-events', [CommerceAgentEventController::class, 'index']);
    Route::get('commerce-events/owner-alerts', [CommerceAgentEventController::class, 'ownerAlerts']);
    Route::post('commerce-events/detect', [CommerceAgentEventController::class, 'detect']);
    Route::post('commerce-events/process-alerts', [CommerceAgentEventController::class, 'processAlerts']);
    Route::post('commerce-events/{id}/acknowledge', [CommerceAgentEventController::class, 'acknowledge']);
    Route::get('integrations', [IntegrationController::class, 'index']);
    Route::post('integrations/connect', [IntegrationController::class, 'connect']);
    Route::post('integrations/sync', [IntegrationController::class, 'sync']);
    Route::delete('integrations/{connectorType}', [IntegrationController::class, 'disconnect']);
    Route::get('knowledge/vector-status', [KnowledgeVectorController::class, 'status']);
    Route::get('company-brain', [CompanyBrainController::class, 'show']);
    Route::post('company-brain/refresh', [CompanyBrainController::class, 'refresh']);
    Route::get('owner-analytics/investigations', [OwnerAnalyticsController::class, 'index']);
    Route::post('owner-analytics/investigate', [OwnerAnalyticsController::class, 'investigate']);
    Route::get('mission-control', [MissionControlController::class, 'index']);
    Route::get('mission-control/explainability/{id}', [MissionControlController::class, 'explainability']);
    Route::get('agent-trust-logs', [AgentTrustLogController::class, 'index']);
    Route::post('memory-search', [MemorySearchController::class, 'search']);
    Route::get('business-timeline', [BusinessTimelineController::class, 'index']);
    Route::post('business-timeline/sync', [BusinessTimelineController::class, 'sync']);
    Route::get('business-graph', [BusinessGraphController::class, 'show']);
    Route::post('business-graph/sync', [BusinessGraphController::class, 'sync']);
    Route::post('business-graph/nodes', [BusinessGraphController::class, 'storeNode']);
    Route::post('onboarding-interview/start', [OnboardingInterviewController::class, 'start']);
    Route::post('onboarding-interview/respond', [OnboardingInterviewController::class, 'respond']);
    Route::get('channels', [ChannelIngestController::class, 'channels']);
    Route::post('channels/ingest', [ChannelIngestController::class, 'ingest']);
    Route::post('channels/regenerate-tokens', [ChannelIngestController::class, 'regenerateTokens']);
    Route::get('marketplace/modules', [MarketplaceController::class, 'catalog']);
    Route::post('marketplace/modules/{moduleKey}/install', [MarketplaceController::class, 'install']);
    Route::delete('marketplace/modules/{moduleKey}/install', [MarketplaceController::class, 'uninstall']);
    Route::get('ai-models', [AiModelController::class, 'index']);
    Route::get('ai-providers', [CompanyAiProviderController::class, 'index']);
    Route::put('ai-providers/{slug}', [CompanyAiProviderController::class, 'update']);
    Route::get('ai-usage', [CompanyAiUsageController::class, 'index']);
    Route::get('whatsapp/status', [WhatsAppController::class, 'status']);
    Route::post('whatsapp/connect', [WhatsAppController::class, 'connect']);
    Route::get('whatsapp/numbers', [WhatsAppController::class, 'numbers']);
    Route::get('whatsapp/embedded/config', [WhatsAppController::class, 'embeddedConfig']);
    Route::post('whatsapp/embedded/complete', [WhatsAppController::class, 'completeEmbeddedSignup']);
    Route::post('whatsapp/disconnect', [WhatsAppController::class, 'disconnect']);
    Route::get('whatsapp/templates', [WhatsAppTemplateController::class, 'index']);
    Route::post('whatsapp/templates', [WhatsAppTemplateController::class, 'store']);
    Route::post('whatsapp/templates/sync', [WhatsAppTemplateController::class, 'sync']);
    Route::delete('whatsapp/templates/{template}', [WhatsAppTemplateController::class, 'destroy']);
    Route::get('whatsapp/campaign/limits', [WhatsAppCampaignController::class, 'limits']);
    Route::get('whatsapp/campaign/audience', [WhatsAppCampaignController::class, 'audience']);
    Route::get('whatsapp/campaign/growth-posts', [WhatsAppCampaignController::class, 'growthPosts']);
    Route::post('whatsapp/campaign/generate-caption', [WhatsAppCampaignController::class, 'generateCaption']);
    Route::post('whatsapp/campaign/send', [WhatsAppCampaignController::class, 'send']);
    Route::get('whatsapp/campaigns', [WhatsAppCampaignController::class, 'index']);
    Route::post('whatsapp/campaigns', [WhatsAppCampaignController::class, 'store']);
    Route::get('whatsapp/campaigns/{campaign}', [WhatsAppCampaignController::class, 'show']);
    Route::patch('whatsapp/campaigns/{campaign}', [WhatsAppCampaignController::class, 'update']);
    Route::post('whatsapp/campaigns/{campaign}/poster', [WhatsAppCampaignController::class, 'uploadPoster']);
    Route::post('whatsapp/campaigns/{campaign}/send', [WhatsAppCampaignController::class, 'sendCampaign']);
    Route::post('whatsapp/campaigns/{campaign}/test', [WhatsAppCampaignController::class, 'testSend']);
    Route::get('learning/export', [\App\Http\Controllers\Api\Company\LearningExportController::class, 'export']);
    Route::post('export', [ExportController::class, 'export']);
    Route::get('export/download/{filename}', [ExportController::class, 'download']);
    Route::post('import/products', [ImportController::class, 'importProducts']);
    Route::post('import/faqs', [ImportController::class, 'importFaqs']);
    Route::post('checkout', [StripeCheckoutController::class, 'createSession']);
    Route::post('billing-portal', [StripeCheckoutController::class, 'createPortalSession']);
    Route::post('mpesa/initiate', [MpesaCheckoutController::class, 'initiate']);
    Route::post('paystack/initialize', [PaystackCheckoutController::class, 'initialize']);
});

// Admin (auth:sanctum + admin role)
Route::prefix('admin')->middleware(['auth:sanctum', 'user.active', 'admin'])->group(function () {
    Route::get('overview', [OverviewController::class, 'index']);
    Route::get('growth-portfolio', [GrowthPortfolioController::class, 'index']);
    Route::post('growth-portfolio/generate', [GrowthPortfolioController::class, 'generateRecommendations']);
    Route::post('growth-portfolio/queue', [GrowthPortfolioController::class, 'queueRecommendations']);
    Route::post('growth-portfolio/recommendations/{recommendation}/read', [GrowthPortfolioController::class, 'markRecommendationRead']);
    Route::post('growth-portfolio/recommendations/{recommendation}/approve', [GrowthPortfolioController::class, 'approveRecommendation']);
    Route::get('system-health', [SystemHealthController::class, 'index']);
    Route::get('whatsapp/connections', [WhatsAppConnectionController::class, 'index']);
    Route::get('companies', [CompanyController::class, 'index']);
    Route::get('companies/{company}', [CompanyController::class, 'show']);
    Route::put('companies/{company}', [CompanyController::class, 'update']);
    Route::patch('companies/{company}', [CompanyController::class, 'updateStatus']);
    Route::get('users', [UserController::class, 'index']);
    Route::patch('users/{user}', [UserController::class, 'updateStatus']);
    Route::post('users/{user}/reset-password', [UserController::class, 'resetPassword']);
    Route::get('subscriptions', [App\Http\Controllers\Api\Admin\SubscriptionController::class, 'index']);
    Route::patch('subscriptions/{subscription}', [App\Http\Controllers\Api\Admin\SubscriptionController::class, 'update']);
    Route::get('plans', [App\Http\Controllers\Api\Admin\PlanController::class, 'index']);
    Route::post('plans', [App\Http\Controllers\Api\Admin\PlanController::class, 'store']);
    Route::put('plans/{plan}', [App\Http\Controllers\Api\Admin\PlanController::class, 'update']);
    Route::delete('plans/{plan}', [App\Http\Controllers\Api\Admin\PlanController::class, 'destroy']);
    Route::get('revenue', [RevenueController::class, 'index']);
    Route::get('ai-usage', [AIUsageController::class, 'index']);
    Route::get('ai-learning/stats', [AiLearningAdminController::class, 'stats']);
    Route::get('ai-learning/samples', [AiLearningAdminController::class, 'listSamples']);
    Route::post('ai-learning/samples/{sample}/review', [AiLearningAdminController::class, 'reviewSample']);
    Route::post('ai-learning/purge', [AiLearningAdminController::class, 'purgeSamples']);
    Route::post('ai-learning/prune-expired', [AiLearningAdminController::class, 'pruneExpired']);
    Route::post('ai-learning/sync-faq-embeddings', [AiLearningAdminController::class, 'syncFaqEmbeddings']);
    Route::post('ai-learning/sync-learning-embeddings', [AiLearningAdminController::class, 'syncLearningEmbeddings']);
    Route::post('ai-learning/sync-product-embeddings', [AiLearningAdminController::class, 'syncProductEmbeddings']);
    Route::get('ai-config', [AiConfigController::class, 'index']);
    Route::get('ai-config/orchestration', [AiConfigController::class, 'orchestration']);
    Route::put('ai-config/providers/{provider}', [AiConfigController::class, 'updateProvider']);
    Route::post('ai-config/models', [AiConfigController::class, 'storeModel']);
    Route::put('ai-config/models/{model}', [AiConfigController::class, 'updateModel']);
    Route::delete('ai-config/models/{model}', [AiConfigController::class, 'destroyModel']);
    Route::get('logs', [LogController::class, 'index']);
    Route::get('payment-gateways', [PaymentGatewayController::class, 'index']);
    Route::put('payment-gateways/{slug}', [PaymentGatewayController::class, 'update']);
    Route::get('settings', [PlatformSettingsController::class, 'show']);
    Route::put('settings', [PlatformSettingsController::class, 'update']);
    Route::post('settings', [PlatformSettingsController::class, 'update']);
    Route::post('settings/test-email', [PlatformSettingsController::class, 'testEmail']);
    Route::post('export', [App\Http\Controllers\Api\Admin\ExportController::class, 'export']);
    Route::get('export/download/{filename}', [App\Http\Controllers\Api\Admin\ExportController::class, 'download']);
    Route::post('impersonate/user/{user}', [ImpersonateController::class, 'impersonateUser']);
    Route::post('impersonate/company/{company}', [ImpersonateController::class, 'impersonateCompany']);
    Route::get('testimonials', [TestimonialController::class, 'index']);
    Route::post('testimonials', [TestimonialController::class, 'store']);
    Route::put('testimonials/{testimonial}', [TestimonialController::class, 'update']);
    Route::delete('testimonials/{testimonial}', [TestimonialController::class, 'destroy']);
    Route::get('landing-faqs', [LandingFaqController::class, 'index']);
    Route::post('landing-faqs', [LandingFaqController::class, 'store']);
    Route::put('landing-faqs/{landing_faq}', [LandingFaqController::class, 'update']);
    Route::delete('landing-faqs/{landing_faq}', [LandingFaqController::class, 'destroy']);
    Route::get('cms/pages', [CmsAdminController::class, 'pages']);
    Route::get('cms/pages/{slug}', [CmsAdminController::class, 'showPage']);
    Route::put('cms/pages/{slug}', [CmsAdminController::class, 'updatePage']);
    Route::put('cms/pages/{slug}/sections/{sectionKey}', [CmsAdminController::class, 'updateSection']);
    Route::put('cms/pages/{slug}/sections-reorder', [CmsAdminController::class, 'reorderSections']);
    Route::post('cms/upload-image', [CmsAdminController::class, 'uploadImage']);
});
