<?php

namespace App\Services\Agent;

use App\Models\Company;
use App\Models\Order;
use App\Services\AI\AiGateway;
use Illuminate\Support\Facades\Log;

/**
 * Event-driven proactive messages generated by the agent (single-shot, no tool loop).
 */
final class AgentProactiveMessageService
{
    public function __construct(
        protected AiGateway $aiGateway,
        protected CustomerMemoryService $customerMemory,
        protected BusinessGoalService $businessGoals,
    ) {}

    public static function isProactiveEnabled(Company $company): bool
    {
        if (! CommerceAgentReplyService::isEnabledForCompany($company)) {
            return false;
        }

        return (bool) ($company->settings?->agent_proactive_enabled ?? false);
    }

    public function paymentReceivedMessage(Order $order): ?string
    {
        $company = $order->company;
        if (! $company || ! self::isProactiveEnabled($company)) {
            return null;
        }

        $company->loadMissing('settings');
        $currency = $company->settings?->displayCurrencyCode() ?? 'USD';
        $context = [
            'event' => 'payment_received',
            'order_number' => $order->order_number,
            'total' => $order->total,
            'currency' => $currency,
            'customer_name' => $order->customer_name,
            'receipt_url' => $order->publicReceiptUrl(),
        ];

        return $this->generate($company, $order->customer_phone, $context, $this->fallbackPaymentMessage($order));
    }

    public function abandonedCartMessage(Order $order): ?string
    {
        $company = $order->company;
        if (! $company || ! self::isProactiveEnabled($company)) {
            return null;
        }

        $company->loadMissing('settings');
        $context = [
            'event' => 'abandoned_cart',
            'order_number' => $order->order_number,
            'total' => $order->total,
            'customer_name' => $order->customer_name,
        ];

        return $this->generate($company, $order->customer_phone, $context, $this->fallbackAbandonedCartMessage($order));
    }

    /**
     * @param  array<string, mixed>  $eventContext
     */
    private function generate(Company $company, ?string $customerPhone, array $eventContext, string $fallback): string
    {
        $memory = $customerPhone
            ? $this->customerMemory->getForPrompt((int) $company->id, $customerPhone)
            : '';
        $goals = $this->businessGoals->getForPrompt($company);

        $system = implode("\n\n", array_filter([
            "You are the business's digital employee on WhatsApp. Write ONE proactive outbound message.",
            'Be warm, concise, and natural. Do not mention AI, tools, or internal systems.',
            $goals,
            $memory,
        ]));

        $user = 'Event context (JSON): '.json_encode($eventContext, JSON_UNESCAPED_UNICODE);

        try {
            $result = $this->aiGateway->chatCompletion(
                [
                    ['role' => 'system', 'content' => $system],
                    ['role' => 'user', 'content' => $user],
                ],
                useCase: 'agent_proactive',
                company: $company,
                maxTokens: 220,
                temperature: 0.5,
                jsonMode: false,
                timeoutSeconds: 20,
            );

            if ($result->success && trim((string) $result->content) !== '') {
                return trim((string) $result->content);
            }
        } catch (\Throwable $e) {
            Log::warning('Agent proactive message generation failed', [
                'company_id' => $company->id,
                'event' => $eventContext['event'] ?? 'unknown',
                'error' => $e->getMessage(),
            ]);
        }

        return $fallback;
    }

    private function fallbackPaymentMessage(Order $order): string
    {
        return "Payment received. Your order #{$order->order_number} is confirmed. Thank you!\n\nView invoice / receipt:\n".$order->publicReceiptUrl();
    }

    private function fallbackAbandonedCartMessage(Order $order): string
    {
        return "Hi! We noticed your order #{$order->order_number} is still awaiting payment. Would you like help completing it? Just reply here and we'll assist you.";
    }
}
