name: CI

on:
  pull_request:
    paths:
      - 'LARAVEL_BACKEND/**'
      - '.github/workflows/ci.yml'
      - '.github/workflows/tests.yml'
      - '.github/workflows/deploy-production.yml'
      - '.github/workflows/deploy-staging.yml'
  push:
    branches-ignore: [main]
    paths:
      - 'LARAVEL_BACKEND/**'
      - '.github/workflows/ci.yml'
      - '.github/workflows/tests.yml'
      - '.github/workflows/deploy-production.yml'
      - '.github/workflows/deploy-staging.yml'

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/tests.yml
